### ISSUE TITLE
Use event stream format? 

### ISSUE THREAD

**Issue by Daniel15** [zaptst/zap#5]
Instead of just using newline delimited JSON, what about using the event stream format from Server Sent Events? 

https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format

That'd give you an easy way to subscribe to updates from JS in a browser, since it's already in a format supported by browsers.

**Comment by jamiebuilds** [comment]
It seems like you could pretty easily build a tool for this, but newline delimited JSON is going to be super easy to parse in every language.
